In [35]:
import math
def basic_sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [36]:
basic_sigmoid(3)

0.9525741268224334

In [37]:
x1=[1,2,3]
import numpy as np
x2=np.array([1,2,3])
print (x1,x2)


[1, 2, 3] [1 2 3]


In [38]:
print(np.exp(x1),np.exp(x2))

[  2.71828183   7.3890561   20.08553692] [  2.71828183   7.3890561   20.08553692]


In [39]:
def sigmoid(x):
    s=1/(1+np.exp(-x))
    return s

In [40]:
print(sigmoid(3))

0.952574126822


In [41]:
print(sigmoid(x2))

[ 0.73105858  0.88079708  0.95257413]


In [42]:
def sigmoid_der(x):
    s=1/(1+np.exp(x))
    ds=s*(1-s)
    return ds

In [43]:
x=np.array([1,2,3])
print("sigmoid_der([1,2,3])= " + str(sigmoid_der(x)))

sigmoid_der([1,2,3])= [ 0.19661193  0.10499359  0.04517666]


In [44]:
def image2vector(image):
    v=image.reshape(image.shape[0]*image.shape[1]*image.shape[2])
    return v

In [45]:
image = np.array(
      [[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [46]:
def normalizeRows(x):
    x_norm=np.linalg.norm(x,ord=2,axis=1,keepdims=True)
    x=x/x_norm
    return x

In [47]:
x=np.array([[0,3,4],[1,6,4]])
print("normalizeRows(x)="+str(normalizeRows(x)))

normalizeRows(x)=[[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [56]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp,axis=1,keepdims=True)
    result=x_exp/x_sum
    return result

In [57]:
x=np.array([[9,2,5,0,0],[7,5,0,0,0]])
print("softmax(x)="+str(softmax(x)))

softmax(x)=[[  9.80897665e-01   8.94462891e-04   1.79657674e-02   1.21052389e-04
    1.21052389e-04]
 [  8.78679856e-01   1.18916387e-01   8.01252314e-04   8.01252314e-04
    8.01252314e-04]]


In [58]:
import time

In [59]:
x1=[9,2,5,0,0,7,5,0,0,0,9,2,5,0,0]
x2=[9,2,2,9,0,9,2,5,0,0,9,2,5,0,0]

In [68]:
tic=time.process_time()
dot=0
for i in range(len(x1)):
    dot+=x1[i]*x2[i]
toc=time.process_time()
print("dot:"+str(dot)+"\ntime:"+str(1000*(toc-tic)))
tic=time.process_time()
dot=np.dot(x1,x2)
toc=time.process_time()
print("dot:"+str(dot)+"\ntime:"+str(1000*(toc-tic)))

dot:278
time:0.2092120000001252
dot:278
time:0.15770800000014518


In [72]:
tic=time.process_time()
outer=np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i][j]=x1[i]*x2[j]
toc=time.process_time()
print("outer:"+str(outer)+"\ntime:"+str(1000*(toc-tic)))
tic=time.process_time()
outer=np.outer(x1,x2)
toc=time.process_time()
print("outer:"+str(outer)+"\ntime:"+str(1000*(toc-tic)))

outer:[[ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  18.   4.  10.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 63.  14.  14.  63.   0.  63.  14.  35.   0.   0.  63.  14.  35.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  18.   4.  10.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  1

In [75]:
tic=time.process_time()
mul=np.zeros(len(x1))
for i in range(len(x1)):
    mul[i]=x1[i]*x2[i]
toc=time.process_time()
print("mul:"+str(mul)+"\ntime:"+str(1000*(toc-tic)))
tic=time.process_time()
mul=np.multiply(x1,x2)
toc=time.process_time()
print("mul:"+str(mul)+"\ntime:"+str(1000*(toc-tic)))

mul:[ 81.   4.  10.   0.   0.  63.  10.   0.   0.   0.  81.   4.  25.   0.   0.]
time:0.12341600000009834
mul:[81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
time:0.09959299999984239


In [85]:
W=np.random.rand(3,len(x1))
tic=time.process_time()
gdot=np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        gdot[i]+=W[i][j]*x1[j]
toc=time.process_time()
print("gdot:"+str(gdot))
print("time:"+str(1000*(toc-tic)))
tic=time.process_time()
gdot=np.dot(W,x1)
toc=time.process_time()
print("gdot:"+str(gdot))
print("time:"+str(1000*(toc-tic)))

gdot:[ 18.94493457  22.77410118  13.62869057]
time:0.1715400000001921
gdot:[ 18.94493457  22.77410118  13.62869057]
time:0.10408599999989221


In [86]:
def L1(yhat,y):
    loss=np.sum(np.abs(yhat-y))
    return loss

In [87]:
yhat=np.array([.9,.2,.1,.4,.9])
y=np.array([1,0,0,1,1])
print("L1:"+str(L1(yhat,y)))

L1:1.1


In [100]:
def L2(yhat,y):
    loss=np.dot(yhat-y,yhat-y)
    return loss

In [101]:
print("L2:"+str(L2(y,yhat)))

L2:0.43
